"""Strategy brief PDF: The London Temperature Edge (2 pages, no cover)."""

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (HRFlowable, KeepTogether, Paragraph,
                                SimpleDocTemplate, Spacer, Table, TableStyle)

# ━━ Color Palette (auto-generated by pdf.py palette.generate) ━━
ACCENT = colors.HexColor('#1e7693')
TEXT_PRIMARY = colors.HexColor('#1f2022')
TEXT_MUTED = colors.HexColor('#6e7479')
BG_SURFACE = colors.HexColor('#dde0e3')
BG_PAGE = colors.HexColor('#ebecee')

FDIR = "/System/Library/Fonts/Supplemental/"
pdfmetrics.registerFont(TTFont('Times New Roman', FDIR + 'Times New Roman.ttf'))
pdfmetrics.registerFont(TTFont('Times New Roman Bold', FDIR + 'Times New Roman Bold.ttf'))
pdfmetrics.registerFont(TTFont('Times New Roman Italic', FDIR + 'Times New Roman Italic.ttf'))
registerFontFamily('Times New Roman', normal='Times New Roman',
                   bold='Times New Roman Bold', italic='Times New Roman Italic')

OUT = "/Users/paretoc4p/.zcode/workspace/default/London_Temperature_Edge_Brief.pdf"
doc = SimpleDocTemplate(OUT, pagesize=A4,
                        leftMargin=2 * cm, rightMargin=2 * cm,
                        topMargin=1.8 * cm, bottomMargin=1.8 * cm,
                        title="The London Temperature Edge - Strategy Brief",
                        author="Z.ai", creator="Z.ai",
                        subject="Polymarket London temperature markets: edge recap and pilot strategy")
AW = doc.width  # available width

kicker = ParagraphStyle('Kicker', fontName='Times New Roman', fontSize=9.5,
                        leading=13, textColor=ACCENT, spaceAfter=4)
title_s = ParagraphStyle('TitleS', fontName='Times New Roman', fontSize=27,
                         leading=31, textColor=TEXT_PRIMARY, spaceAfter=6)
meta_s = ParagraphStyle('MetaS', fontName='Times New Roman', fontSize=9.5,
                        leading=13, textColor=TEXT_MUTED, spaceAfter=2)
h1 = ParagraphStyle('H1', fontName='Times New Roman', fontSize=14, leading=18,
                    textColor=ACCENT, spaceBefore=14, spaceAfter=6)
body = ParagraphStyle('Body', fontName='Times New Roman', fontSize=10.5,
                      leading=15.5, textColor=TEXT_PRIMARY,
                      alignment=TA_JUSTIFY, spaceAfter=7)
bullet = ParagraphStyle('Bullet', fontName='Times New Roman', fontSize=10.5,
                        leading=15, textColor=TEXT_PRIMARY, leftIndent=12,
                        spaceAfter=4)
stat_big = ParagraphStyle('StatBig', fontName='Times New Roman', fontSize=17,
                          leading=20, textColor=ACCENT, alignment=TA_CENTER)
stat_lab = ParagraphStyle('StatLab', fontName='Times New Roman', fontSize=8,
                          leading=10.5, textColor=TEXT_MUTED, alignment=TA_CENTER)
th = ParagraphStyle('TH', fontName='Times New Roman', fontSize=9.5, leading=12,
                    textColor=colors.white, alignment=TA_LEFT)
tc = ParagraphStyle('TC', fontName='Times New Roman', fontSize=9.5, leading=12.5,
                    textColor=TEXT_PRIMARY, alignment=TA_LEFT)
tcm = ParagraphStyle('TCM', fontName='Times New Roman', fontSize=9.5, leading=12.5,
                     textColor=TEXT_PRIMARY, alignment=TA_CENTER)

story = []

# ── header ──
story.append(Paragraph('STRATEGY BRIEF · FOR PARTNER REVIEW', kicker))
story.append(Paragraph('<b>The London Temperature Edge</b>', title_s))
story.append(Paragraph('Polymarket daily weather markets · what we found and how we will trade it · 23 August 2026', meta_s))
story.append(Spacer(1, 4))
story.append(HRFlowable(width='100%', thickness=1.4, color=ACCENT, spaceAfter=12))

# ── plain-terms summary ──
story.append(Paragraph('<b>In plain terms</b>', h1))
story.append(Paragraph(
    'We built a free, self-running data system that tracks Polymarket’s daily London '
    'temperature betting markets. It now holds nineteen months of history: every trade, every '
    'price, and the actual airport weather observations that these bets officially settle on. '
    'Across roughly 700 past events and about 90 million dollars of trading, we found that the '
    'market’s opening odds are consistently slower and less accurate than the free official '
    'Met Office weather forecast. On average the market misses the day’s high temperature by '
    'about one degree Celsius; the model misses by less than half that.', body))
story.append(Paragraph(
    'So we tested the simplest possible strategy against history: each day, bet on the '
    'temperature band the official model predicts. It would have won about 60 percent of the '
    'time, at an average price of about 35 cents, returning roughly one dollar of profit for '
    'every dollar staked. Even entering realistically the day before, after the fresh forecasts '
    'come out, the return holds at about 90 cents to 1.10 per dollar.', body))
story.append(Paragraph(
    'The honest caveats: this is historical backtesting that assumes we can trade near the last '
    'traded price; the edge will shrink if other people catch on; and no money is at risk until '
    'a small live pilot confirms the numbers over four to six weeks.', body))

# ── stat callouts ──
def callout(num, lab):
    t = Table([[Paragraph('<b>%s</b>' % num, stat_big)], [Paragraph(lab, stat_lab)]],
              colWidths=[AW / 3.0 - 10])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), BG_PAGE),
        ('BOX', (0, 0), (-1, -1), 0.8, ACCENT),
        ('TOPPADDING', (0, 0), (0, 0), 7), ('BOTTOMPADDING', (0, 0), (0, 0), 1),
        ('TOPPADDING', (0, 1), (0, 1), 1), ('BOTTOMPADDING', (0, 1), (0, 1), 7),
    ]))
    return t

row = Table([[callout('60%', 'win rate across 490 backtested events'),
              callout('+$1.09 / $1', 'realistic entry, day before, after fresh forecasts'),
              callout('0.47°C vs 1.09°C', 'model vs market error on the daily high')]],
            colWidths=[AW / 3.0] * 3, hAlign='CENTER')
row.setStyle(TableStyle([('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                         ('LEFTPADDING', (0, 0), (-1, -1), 5),
                         ('RIGHTPADDING', (0, 0), (-1, -1), 5)]))
story.append(Spacer(1, 6))
story.append(row)
story.append(Spacer(1, 4))

# ── the edge in numbers ──
story.append(Paragraph('<b>The edge in numbers</b>', h1))
edge_rows = [
    ['What we measured', 'Result'],
    ['Forecast accuracy, daily high (model vs market at open)', '0.47°C vs 1.09°C error'],
    ['Model beats the market’s opening price, head-to-head', '66% of events (395 vs 149 of 594)'],
    ['Backtest: buy the model band at market open, hold to resolution',
     '60% win rate at 30¢ median entry; +$2.79 per $1 (490 events)'],
    ['Same strategy with the 10–50¢ entry filter we will actually use', '+$1.37 per $1'],
    ['Market’s own favorite bought at open (control)', 'Loses money (−$0.15 per $1)'],
    ['Consistency across eras', '+$2.70/$1 in 2025; +$2.84/$1 in 2026'],
    ['Worst losing streak observed', '6 events in a row'],
]
tdata = [[Paragraph('<b>%s</b>' % c, th), Paragraph('<b>%s</b>' % r, th)] for c, r in [edge_rows[0]]] + \
        [[Paragraph(a, tc), Paragraph(b, tcm)] for a, b in edge_rows[1:]]
col_r = [0.58, 0.42]
t = Table(tdata, colWidths=[r * AW for r in col_r], hAlign='CENTER')
style_cmds = [('BACKGROUND', (0, 0), (-1, 0), ACCENT),
              ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
              ('GRID', (0, 0), (-1, -1), 0.4, TEXT_MUTED),
              ('LEFTPADDING', (0, 0), (-1, -1), 7), ('RIGHTPADDING', (0, 0), (-1, -1), 7),
              ('TOPPADDING', (0, 0), (-1, -1), 4.5), ('BOTTOMPADDING', (0, 0), (-1, -1), 4.5)]
for i in range(1, len(tdata)):
    style_cmds.append(('BACKGROUND', (0, i), (-1, i),
                       colors.white if i % 2 == 1 else BG_PAGE))
t.setStyle(TableStyle(style_cmds))
story.append(t)
story.append(Spacer(1, 5))
story.append(Paragraph('All figures from our own dataset: 707 events, Jan 2025 to Aug 2026, '
                       'verified against London City airport (EGLC) METAR observations.',
                       ParagraphStyle('Cap', parent=meta_s, alignment=TA_CENTER)))

# ── page 2: strategy rules ──
story.append(KeepTogether([
    Paragraph('<b>The strategy we start with</b>', h1),
    Paragraph(
        'One rule, mechanically applied: <b>trade the Met Office, not the crowd.</b> Every London '
        'temperature event, buy the band containing the official forecast, at a price the market '
        'has not caught up to, and hold to resolution.', body)]))
rules = [
    ['Rule', 'What we do'],
    ['Signal', 'Free Met Office model forecast (via Open-Meteo), pinned to the airport the market settles on'],
    ['Entry', 'The day before the event, 11:00–13:00 UTC, after fresh model runs land; buy the forecast band priced 10–50¢'],
    ['Sizing', 'Flat base stake (£50 per event in the pilot) × regime multiplier: full stake when models mildly disagree (0.5–1.0°C), half or quarter when they disagree more'],
    ['Exit', 'Hold to resolution; if a fresh forecast run moves the band, roll the position to the new band'],
    ['Risk', 'One band per event, no averaging down; stake capped at 1/20 of bankroll; automatic stop if the trailing 30-event win rate falls below 45%'],
    ['Non-goals', 'No market making, no intraday trading, no paid data — deliberately boring'],
]
rdata = [[Paragraph('<b>%s</b>' % c, th), Paragraph('<b>%s</b>' % r, th)] for c, r in [rules[0]]] + \
        [[Paragraph('<b>%s</b>' % a, tc), Paragraph(b, tc)] for a, b in rules[1:]]
t2 = Table(rdata, colWidths=[0.16 * AW, 0.84 * AW], hAlign='CENTER')
style_cmds = [('BACKGROUND', (0, 0), (-1, 0), ACCENT),
              ('VALIGN', (0, 0), (-1, -1), 'TOP'),
              ('GRID', (0, 0), (-1, -1), 0.4, TEXT_MUTED),
              ('LEFTPADDING', (0, 0), (-1, -1), 7), ('RIGHTPADDING', (0, 0), (-1, -1), 7),
              ('TOPPADDING', (0, 0), (-1, -1), 4.5), ('BOTTOMPADDING', (0, 0), (-1, -1), 4.5)]
for i in range(1, len(rdata)):
    style_cmds.append(('BACKGROUND', (0, i), (-1, i),
                       colors.white if i % 2 == 1 else BG_PAGE))
t2.setStyle(TableStyle(style_cmds))
story.append(t2)
story.append(Spacer(1, 6))

story.append(KeepTogether([
    Paragraph('<b>Why timing matters (and why we are not too late)</b>', h1)]))
story.append(Paragraph(
    'The win rate barely changes as the event approaches — about 61% whether we enter two '
    'days out or one day out. What changes is the price of the correct band, which climbs from '
    '30¢ toward 50¢ as the market slowly catches up. The edge does not disappear; it gets '
    'priced in gradually. That is why the day-before entry, after the freshest forecasts, still '
    'returns about one dollar per dollar staked.', body))

story.append(KeepTogether([Paragraph('<b>Honest caveats</b>', h1),
                             Paragraph('•  ' + 'Backtest assumes fills near the last traded price; real fills will be somewhat worse. Thin books are both the opportunity and the risk.', bullet)]))
for b_ in [
    'The edge exists because the market ignores free information. If faster traders arrive, it decays — the automatic stop rule exists to catch exactly that.',
    'A 60% strategy still loses 4 times in 10. Single days prove nothing; only the 4-to-6 week pilot total counts.',
    'Nothing here is live. No money is at risk until the pilot begins, and the pilot is the only remaining step before any scale-up decision.',
]:
    story.append(Paragraph('•  ' + b_, bullet))

story.append(KeepTogether([
    Paragraph('<b>The pilot</b>', h1),
    Paragraph(
    '£50 per event for four to six weeks (40+ events), executed manually at about one '
    'minute per day. Every entry is logged automatically against the dataset we already '
    'collect nightly, so realised results are compared directly with the backtest promise. '
    'Success bar: at least +$0.80 per $1 realised. Clear it, and we scale in doubled steps; '
    'miss it, and we stop with a cheap education and keep the dataset.', body)]))

story.append(Spacer(1, 10))
story.append(HRFlowable(width='100%', thickness=0.7, color=BG_SURFACE, spaceAfter=5))
story.append(Paragraph('Data: Polymarket public APIs · Met Office model via Open-Meteo · EGLC METAR observations '
                       '(Iowa Environmental Mesonet) · collected and verified nightly, automatically.', meta_s))

doc.build(story)
print('built', OUT)
